### PR TITLE
Apply fix to read output state of a GPIO successfully

### LINKED ISSUE #17: ESP32-C3 GPIO's `is_set_high` and `is_set_low` functions always return `false`/`true` respectively
This is a strange issue, as I have had this working before.

My application runs as expected, with the exception that the LED does not blink. The loop index is printed over serial for each iteration of the loop as intended. I have confirmed my hardware and test setup are okay by flashing the `blinky` example from `esp-idf`, which worked as expected.

I have added the minimal project to a repository, generated from `esp-idf-template`:  
https://github.com/jessebraham/esp32c3-idf-hal-test

Rust nightly version is quite new:

```shell
λ rustc +nightly --version
rustc 1.59.0-nightly (48a5999fc 2021-12-01)
```

I'm hoping I'm missing something silly here, but I have tried using multiple GPIOs, tried resetting the pin first, all to no avail.

### PR DESCRIPTION
**Pull request by jessebraham**
Since we are not reliably able to read the output state with the existing implementation, I've just dropped down a level and read the `GPIO_OUT_REG` register directly. This is a bit ugly, but the `StatefulOutputPin` and `ToggleableOutputPin` trait implementations are now working as expected. If there is a function in `esp-idf-sys` which will do this please let me know, but I did not see one.

This has been tested on the ESP32, ESP32-C3, and ESP32-S2. Just to note, I did try testing the ESP32-S3 as well but encountered an error originating from `esp-idf-sys` saying that PIO did not have a matching definition for the ESP32-S3.

Fixes #17

### CODE REVIEW

File: src/gpio.rs [hunk 1]
```diff
@@ -238,7 +238,10 @@ macro_rules! impl_hal_output_pin {
 
         impl embedded_hal::digital::v2::StatefulOutputPin for $pxi<$mode> {
             fn is_set_high(&self) -> Result<bool, Self::Error> {
-                Ok(unsafe { gpio_get_level($pxi::<$mode>::runtime_pin()) } != 0)
```
Comment (ivmarkov) [inline src/gpio.rs:241]: Ha!! I was working on almost the same solution, except being unnecessary more complicated! :)

Anyway, following issue: at least on esp32 (and I suspect on esp32s2 and esp32s3) the pins are actually > 32, so for pins with number >= 32 you have to do the same shifting trick but against GPIO_OUT1_REG, and subtract 32 from the pin before doing the shift, as described [here](https://esp32.com/viewtopic.php?t=5793#p38567).

Comment (ivmarkov) [reply src/gpio.rs:241]: You can conditionalize the code for pins > 32 by using `#[cfg(not(esp32c3))]` I guess.

**Review by ivmarkov — CHANGES_REQUESTED** [review]

File: src/gpio.rs (hunk 1 above)
Comment (jessebraham) [reply src/gpio.rs:241]: Ahh my mistake, I only tried lower-numbered GPIOs so I guess that's why it worked :)

I'll get it fixed up soon, thanks for pointing that out.

**Comment by ivmarkov** [comment]
> I did try testing the ESP32-S3 as well but encountered an error originating from `esp-idf-sys` saying that PIO did not have a matching definition for the ESP32-S3.

[Hm. Should be supported at least as a "preview" in ESP-IDF V4.3.1 which is used by PlatformIO](https://github.com/espressif/esp-idf#esp-idf-release-and-soc-compatibility).

Can you try using esp32s3 with `cargo build --features native`, __and__ before that - uncommenting `ESP_IDF_VERSION=master` or `ESP_IDF_VERSION=release/v4.4` in `.config/cargo.toml` of your binary crate project?

**Comment by ivmarkov** [comment]
Thanks! Will publish a new version tmr, together with the new esp idf sys.
