### PR TITLE
Reset GPIO pins prior to setting them as inputs or outputs

### LINKED ISSUE #9: ESP32C3 GPIO4 and GPIO5 not working
I'm an unable to control GPIO 4 and 5. Matrix user jessebraham was able to reproduce this.
Other GPIOs behave as expected (using the same code as for GPIO4 and 5)

### PR DESCRIPTION
**Pull request by jessebraham**
This should fix #9 as far as I can tell. Did some quick testing on various pins for the ESP32 and ESP32-C3, everything seems happy. ~~I'm unfortunately unable to use the `reset` function in the various `into_` functions because it takes `&mut self`.~~

### CODE REVIEW

File: src/gpio.rs [hunk 1]
```diff
@@ -413,6 +413,7 @@ macro_rules! impl_input_only {
             }
 
             pub fn into_input(self) -> Result<$pxi<Input>, EspError> {
+                esp_result!(unsafe { gpio_reset_pin($pxi::<MODE>::runtime_pin()) }, ())?;
```
Comment (MabezDev) [inline src/gpio.rs:416]: I haven't tried it, but can you use `self.reset` if you declare the signature as `pub fn into_input(mut self) -> Result<$pxi<Input>, EspError> {`?

Comment (jessebraham) [reply src/gpio.rs:416]: I believe that should work. The less invasive change would probably be to change `reset`, as we define the trait it originates from (`Pin`) and it doesn't have any real reason to be `&mut`.

Comment (MabezDev) [reply src/gpio.rs]: I think we can keep `Pin`'s `reset()` taking `&mut` because our `into_*` methods are taking `self`. Changing the mutability of an owned object doesn't actually change the function signature which is pretty cool! Demo of what I mean here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d69f40daa82052b61841c20fb8ce7f35

Comment (jessebraham) [reply src/gpio.rs]: Interesting, thanks for sharing!

I guess my argument for keeping this PR as-is would simply be that there's not really any reason for `reset()` to be `&mut` regardless, is there? It's not mutating the objects which implement `Pin` in any way, so it just seems unnecessary. Not against reverting though, if we feel that's the better option.

Comment (ivmarkov) [reply src/gpio.rs]: It is not mutating the Rust wrapper objects, but *logically* - it does mutate the pin, in that it changes its state.
So I think it is better if it this is reflected with `&mut` in the function signature IMO.

Basically the same as all other "mutating" methods, like `set_low`, `set_high` and so on.

File: src/gpio.rs [hunk 2]
```diff
@@ -121,8 +121,8 @@ where
         self.pin
     }
 
-    fn reset(&mut self) -> Result<(), Self::Error> {
-        Ok(())
+    fn reset(&self) -> Result<(), Self::Error> {
+        esp_result!(unsafe { gpio_reset_pin(self.pin) }, ())
```
Comment (ivmarkov) [inline src/gpio.rs:125]: We need to guard this with `#[cfg(not(feature = "ulp"))]` As I don't think there is a `gpio_reset_pin` in the "mini" HAL.

Comment (ivmarkov) [reply src/gpio.rs:125]: It was my mistake that the CI does not have a build with `--features ulp`, but I just added it.

**Review by ivmarkov — CHANGES_REQUESTED** [review]

File: src/gpio.rs (hunk 2 above)
Comment (ivmarkov) [reply src/gpio.rs:125]: And then, yeah, I feel `&mut` is kinda OK here :)

**Comment by jessebraham** [comment]
Sorry for making a bit of a mess with this PR. Since I rebased, I went ahead squashed my changes since there were 3 commits doing essentially the same thing. I believe things should be as requested now.

**Comment by ivmarkov** [comment]
@jessebraham just to confirm - you do have committer access, right? so that you can merge changes yourself if I'm not around?

You might want to also update the `esp-idf-hal` version in `Cargo.toml` from time to time and then hit 'Publish` in the Github Actions, so that we have new releases.

**Comment by jessebraham** [comment]
@ivmarkov Yes I do, I have full admin access. Now that I'll be playing with this crate more I'm more than happy to do that!
