### PR TITLE
fix clock usage in timer driver for idf 5

### LINKED ISSUE #426: esp32c2 generated bindgen doesn't include APB_CLK_FREQ correctly
The APB_CLK_FREQ for the c2 is defined [here](https://github.com/espressif/esp-idf/blob/v5.2.1/components/soc/esp32c2/include/soc/soc.h#L149), but for some reason it is not included when building against ESP_IDF_VERSION=v5.2.1. 

This is a problem since we use it in [timer.rs](https://github.com/esp-rs/esp-idf-hal/blob/master/src/timer.rs#L134)

### PR DESCRIPTION
**Pull request by Vollbrecht**
Newer esp's (c2/h2/c6) don't use the apb clock as a default clock for the timer. They use different variants of the pll clock. Furthermore the general assumption that the xtal clock is always 40Mhz is not correct. This PR includes fixes for the TimeDriver in this respect.

closes #426

### CODE REVIEW

File: src/timer.rs [hunk 1]
```diff
@@ -58,12 +59,74 @@ pub mod config {
...
+                #[cfg(not(esp32))]
                 xtal: false,
                 auto_reload: false,
             }
         }
     }
+
+    #[cfg(not(esp_idf_version_major = "4"))]
+    #[allow(clippy::upper_case_acronyms)]
+    pub(crate) enum ClockSource {
```
Comment (ivmarkov) [inline src/timer.rs:71]: Nit: why `pub(crate)`?

File: src/timer.rs [hunk 2]
```diff
@@ -58,12 +59,74 @@ pub mod config {
...
+        #[cfg(esp32h2)]
+        PLL48,
+        #[cfg(esp32c6)]
+        PLL80,
+        #[cfg(not(esp32))]
+        XTAL,
+    }
+
+    #[cfg(not(esp_idf_version_major = "4"))]
+    impl Default for ClockSource {
```
Comment (ivmarkov) [inline src/timer.rs:85]: Nit: you can replace all of this with just `#[default]` above, because for each MCU you end up with exactly two members of the enum, where the `XTAL` member should always be the non-default one.

**Comment by ivmarkov** [comment]
Just two nits. I think you can merge without addressing these either, as they are nits.

File: src/timer.rs (hunk 2 above)
Comment (Vollbrecht) [reply src/timer.rs]: done

File: src/timer.rs (hunk 1 above)
Comment (ivmarkov) [reply src/timer.rs:72]: I meant why is it with a crate visibility and not **private**, but then again - just a nit.
